# Generated by Django 2.2.19 on 2022-03-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id',
                 models.AutoField(
                     auto_created=True,
                     primary_key=True,
                     serialize=False,
                     verbose_name='ID')),
                ('title',
                 models.CharField(
                     max_length=10)),
                ('slug',
                 models.SlugField(
                     max_length=100)),
                ('description',
                 models.TextField()),
            ],
        ),
    ]
